### ISSUE TITLE
SDK报错

### ISSUE THREAD

**Issue by wangjintao** [woncan/WHand#2]
您好，我在使用SDK过程中发生了报错，导致APP崩溃，报错信息如下：
java.lang.NullPointerException: Attempt to read from field 'java.lang.Object java.util.LinkedList$Node.item' on a null object reference
	at java.util.LinkedList.unlink(LinkedList.java:211)
	at java.util.LinkedList.remove(LinkedList.java:526)
	at do.do.do.for.if.run(:30)

**Comment by wangjintao** [comment]
用最新版的1.2.1还是会报这个错，除了这个还有个下标的问题：
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.LinkedList.checkElementIndex(LinkedList.java:555)
	at java.util.LinkedList.remove(LinkedList.java:525)
	at do.do.do.for.if.run(:30)
